-- Public recipe sharing.
-- A recipe is shared when share_token is set: anyone holding the token can read
-- a public-safe projection of the recipe via GET /v1/public/recipes/{token}.
-- The token is generated by the API (cryptographically random, >= 128 bits,
-- base64url) and is the only secret protecting the shared recipe. Setting it
-- back to NULL revokes the link; sharing again issues a brand-new token.
ALTER TABLE recipes ADD COLUMN share_token TEXT;

-- Unique lookup by token; partial so the many unshared (NULL) rows are not indexed.
CREATE UNIQUE INDEX idx_recipes_share_token
    ON recipes (share_token)
    WHERE share_token IS NOT NULL;
